patch upstream
trusty-ia/trusty_app_keymaster pull request #11
Opened 2019-05-24 06:16 UTC by swei22

revert unused patch
fix KW issues

Signed-off-by: Yan, Shaopu <shaopu.yan@intel.com>
Signed-off-by: Sheng, Wei <w.sheng@intel.com>

2019-05-24 06:23 UTC, sysopenci reviewed
Autobuild started from pull-request-changes on this PR.

FAILURE: CheckBug Bad comments/Bugs

For more information, see: /absp/builders/celadon-autobuild/builds/869

2019-05-28 05:40 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/519

2019-05-28 07:54 UTC, fofeir approved these changes

2019-05-28 07:57 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/520

2019-05-28 08:25 UTC, sysopenci reviewed
Autobuild started from pull-request-changes on this PR.

Cactus automatically verified this PR.

For more information, see: /absp/builders/celadon-autobuild/builds/883

2019-05-28 08:28 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/521

2019-05-28 08:49 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/522

2019-05-28 08:58 UTC, bzhu5 commented
not use "fix KW issues".. saying the issues you are going to fix.

2019-05-28 09:03 UTC, bingzhux requested changes
just fix the patch descriptions, then everything else looks good to me.

2019-05-28 09:08 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/523

2019-05-28 09:18 UTC, bingzhux approved these changes

2019-05-28 09:19 UTC, bingzhux approved these changes

2019-05-28 09:21 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/524

2019-05-28 09:28 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/525

2019-05-29 00:56 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/526

2019-05-29 01:43 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/527

2019-05-29 08:13 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/529

2019-05-29 08:32 UTC, fofeir approved these changes

2019-05-29 10:34 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/530

Done by "Sheng, W" <w.sheng@intel.com>

2019-05-29 10:46 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/celadon-premerge/builds/251

Done by "Sheng, W" <w.sheng@intel.com>

2019-05-29 12:57 UTC, merged

2019-05-29 12:58 UTC, sysopenci reviewed
cactus finished building and testing your changes 

It was requested for merge by "Sheng, W" <w.sheng@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp/builders/celadon-mergerequest/builds/837